# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 15s
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
# scrape_configs:
#   # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
#   - job_name: 'prometheus'

#     # metrics_path defaults to '/metrics'
#     # scheme defaults to 'http'.

#   - job_name: 'machine_stats'
#     static_configs:
#       - targets: ['192.168.253.144:9100']

#   - job_name: 'facebook'
#     static_configs:
#       - targets: ['192.168.253.144:5000']
scrape_configs:
    - job_name: 'faces'
      static_configs:
        - targets: ['faces-exporter:9901']
      scrape_interval: 1s
